### ISSUE TITLE
Incorrect shift-reduce conflict resolution with precedence specifier

### ISSUE THREAD

**Issue by RomaVis** [dabeaz/ply#101]
Hi,

While learning to use PLY and experimenting with it I've ran into strange issue. My grammar has simple shift-reduce conflicts that I try to resolve via precedence specification. However, the resolution path taken by PLY seems to be incorrect: PLY chooses to reduce rule instead of shifting next token, although token is of higher priority than the rule used for reduction.

The issue is illustrated in attached files with a bit modified classical 'dangling else' problem
[issue.zip](https://github.com/dabeaz/ply/files/509572/issue.zip)

**Archive contains**

1. lexer.py and parser.py (bare minimum)
2. parser.out (generated by PLY 3.9 from PyPI)
3. bisontest.y (Yacc grammar - the same as in parser.py)
4. y.output generated by Yacc, bisontest.output generated by Bison

**What seems wrong**

The grammar part in question is (_it's a pointless grammar only for illustrative purposes_):
```
if_stmt      :   IF stmt ELSE stmt FI
             |   IF stmt                 %prec IFX
```
Token ELSE has higher precedence than IFX:
```
precedence = (
    ('nonassoc',    'IFX'),
    ('nonassoc',    'ELSE'),
)
```
As such, I expect rule `if_stmt -> IF stmt` to have less priority than token ELSE, so shift-reduce conflict should be resolved by shifting (per documentation):
`If the current token has higher precedence than the rule on the stack, it is shifted.`
However, when shift-reduce conflict arises (state 11 in parser.out) PLY chooses to reduce using production `if_stmt -> IF stmt` instead of shifting ELSE token:
```
state 11
    (6) if_stmt -> IF stmt . ELSE stmt FI
    (7) if_stmt -> IF stmt .
    ELSE            reduce using rule 7 (if_stmt -> IF stmt .)
  ! ELSE            [ shift and go to state 14 ]
    ...
```
Yacc and Bison, on the other hand, decide to shift token (see state 9 both in y.output and bisontest.output).

What's interesting is that if order of rules is reversed, PLY makes a decision to shift.
I.e. rewriting grammar the following way
```
if_stmt      :   IF stmt                 %prec IFX
             |   IF stmt ELSE stmt FI
```
produces:
```
state 9
    (6) if_stmt -> IF stmt .
    (7) if_stmt -> IF stmt . ELSE stmt FI
    ELSE            shift and go to state 13
  ! ELSE            [ reduce using rule 6 (if_stmt -> IF stmt .) ]
    ...
```

Is it a bug?

Thanks,
Roman

**Comment by dabeaz** [comment]
Interesting.  Don't know if it's a bug, but it looks fishy. Will require some investigation.

Related comment:  Why not let PLY just run with it's normal behavior?  The default action is to shift.  It should parse this case correctly even with the 1 shift/reduce conflict.

**Comment by RomaVis** [comment]
Sure, I can leave it to be resolved by default, but I just don't like to see warnings on conflicts.

I'm trying to understand the reasoning behind this behavior by myself, and seems the cause is in lines 2588-2589 at yacc.py:
```
sprec, slevel = Productions[st_actionp[a].number].prec
rprec, rlevel = Precedence.get(a, ('right', 0))
```
This piece of code gets executed when in current state `I` reduce by rule `p` should be performed once token `a` is seen during lookahead, but there's already a shift action assigned to token `a`, so we have a shift-reduce conflict (and shift action comes from production `st_actionp[a]`).

What I don't understand is why it determines shift/reduce precedences like this:

1. Shift precedence is the precedence of the **rule** from which shift action was derived (`Productions[st_actionp[a].number]`)
2. Reduce precedence is the precedence of **token** `a`

Instead, following seems more correct to me:

1. Shift precedence is the precedence of **token** `a`
2. Reduce precedence is the precedence of the **rule** which is reduced (`Productions[p.number]`)

So the code may be changed this way:
```
sprec, slevel = Precedence.get(a, ('right', 0))
rprec, rlevel = Productions[p.number].prec
```

**Comment by dabeaz** [comment]
One thing I'm not completely sure about is what it means to have multiple levels of "nonassoc" precedence.  Bison seems to have a more generic "precedence" specifier that changes the level, but doesn't say anything about associativity.   Maybe PLY should have that too.

Anyways, going to investigate.  Given the age of PLY and the fact that the behavior has probably been around since the beginning, I need to tread carefully on any changed code.

**Comment by dabeaz** [comment]
First, major props for finding and fixing this.  This is 15-year old bug in PLY undiscovered until now (I just checked version 1.0 and it also does this).   The behavior can also be found in the ply/example/calc example if you simply type in this example:

calc > -3 - 4
1
calc >

It gets the wrong answer because it resolves the precedence on the unary minus operator incorrectly.  Yikes!

I've pushed a change and updated the version number.  Would like you give you name credit for this in the CHANGES file. Let me know what to put there (have linked your GitHub profile for now).

**Comment by RomaVis** [comment]
Thanks for fast response!

Will check updated version soon, and close issue afterwards.
As for changelog, my name is Roman Dobrodii. You can put it into file if you want.

**Comment by RomaVis** [comment]
Tested 3.10, and the issue is gone. Thanks!

**Comment by abatta-godo** [comment]
After this fix went in, it stopped working for me.
I understand the issue and I was observing the  warning of shift/reduce conflict. But since it was resolved with shift it worked fine for me.
After upgrading from 3.9 to 3.10 it stopped working and I get parser error on  ELSE Token.
Clearly its reducing instead of shifting.
I thought the default behavior wont change here. Do I need to now use precedence for non_assoc

**Comment by dabeaz** [comment]
This bug was fixed nearly two years ago and fixed a critical issue.   I would need to see a specific code example to investigate.  However, it's not something that I'm going to revert.
