### ISSUE TITLE
problem with %prec

### ISSUE THREAD

**Issue by yoch** [dabeaz/ply#163]
Hi,

I have a weird problem with `%prec`.

Here is a minimal example : __calc1.py__ and __calc2.py__ (see code below) define the same grammar and the same precedence rules in two forms, but calc1.py gives the (correct) AST :

```
> 1*2+3*4
('+', ('*', 1, 2), ('*', 3, 4))
```

and calc2.py gives this one : 

```
> 1+2*3+4
('*', ('+', ('*', 1, 2), 3), 4)
```

### calc1.py
```python
import ply.lex as lex
import ply.yacc as yacc

tokens = ('NUM',)
literals = ('+', '*')
t_NUM = r'\d+'

# Build the lexer
lexer = lex.lex()


precedence = (
    ('left', '+'),
    ('left', '*'),
)

def p_expr_add(p):
    "expr : expr '+' expr"
    p[0] = (p[2], p[1], p[3])

def p_expr_mul(p):
    "expr : expr '*' expr"
    p[0] = (p[2], p[1], p[3])

def p_expr_num(p):
    "expr : NUM"
    p[0] = int(p[1])

# Build the parser
parser = yacc.yacc()

while True:
    s = input('> ')
    ast = parser.parse(s)
    print(ast)
```

### calc2.py

```python
import ply.lex as lex
import ply.yacc as yacc

tokens = ('NUM',)
literals = ('+', '*')
t_NUM = r'\d+'

# Build the lexer
lexer = lex.lex()

precedence = (
    ('left', 'ADD'),
    ('left', 'MUL'),
)

def p_expr_add(p):
    "expr : expr '+' expr %prec ADD"
    p[0] = (p[2], p[1], p[3])

def p_expr_mul(p):
    "expr : expr '*' expr %prec MUL"
    p[0] = (p[2], p[1], p[3])

def p_expr_num(p):
    "expr : NUM"
    p[0] = int(p[1])

# Build the parser
parser = yacc.yacc()

while True:
    s = input('> ')
    ast = parser.parse(s)
    print(ast)
```

**Comment by dabeaz** [comment]
That is indeed pretty strange and I've done a bit of digging into it.   I don't think it's a bug, but it's pretty obscure and it involves some underlying assumptions about how precedence works in yacc.  As reference, I'm going to cite http://www.gnu.org/software/bison/manual/html_node/How-Precedence.html#How-Precedence

The main problem here concerns "The first effect of the precedence declarations is to assign precedence levels to the terminal symbols declared."  Since the actual terminal symbols ('+', '*') aren't listed in the precedence table, they never actually get a precedence level assigned.  Instead, it's only the rule that gets assigned a precedence via %prec.  Since the rule is the only thing that ends up with a precedence level, the behavior is to always reduce the rule no matter what (since it always wins over any token on the input).   Naturally, this leads to some pretty strange AST results.

I don't see how this could really be fixed or reconciled.  Precedence resolution requires that tokens/terminals get assigned precedence values.  The only way for that to happen is for them to be explicitly listed in the precedence table as you did for calc1.py.

**Comment by yoch** [comment]
I understand, thank you for the explanation.

It's a problem for the mini regex grammar I'm trying to write: 

```
expr    : expr '|' expr
        | expr expr
        | expr OP
        | '(' expr ')'
        | CHAR
```

with these precedence rules: 

```
precedence = (
    ('left', 'UNION'),
    ('left', 'CAT'),
    ('noassoc', 'OP')
)
```

and this rule for `CAT`

```
expr : expr expr %prec CAT
```

If I understand correctly, there is no way to fix this grammar because no terminal is defined in `CAT` ?

**Comment by dabeaz** [comment]
Does the grammar work if you simply leave the %prec CAT specifier off?   It might report a "shift/reduce" conflict, but still do the right thing in the end (not all SR conflicts are bad).

It's still possible a %prec CAT could work, but keep in mind the decision to reduce "expr expr" also involves the precedence of the next token on the input.  You might have to do some kind of really strange fiddling around with that--for example, maybe also assigning a precedence level to CHAR or something.

**Comment by yoch** [comment]
I tried to add `CAT` precedence, and surprisingly it worked.

I don't sure that I clearly understand what happen, in particular since CAT is now reduced from right, contrarily to my specification.
