### ISSUE TITLE
Tie-breaking rules issue?

### ISSUE THREAD

**Issue by apanagopoulos** [dabeaz/ply#186]
Hi all,

I have been playing around with the priority in tie-braking and it seems inconsistent. In particular, the following:

`import`` ply.lex as lex
tokens = ('Class1', 'Class2', 'Class3', 'Class4', 'Class5', 'Class6')

t_Class1 = 'aab'
t_Class2 = 'aab | aab'
t_Class3 = 'aab | aab'
t_Class4 = 'aab | aab'
t_Class5 = 'aab*'
t_Class6 = 'aab+'

def t_error( t ):
  print("Invalid Token:",t.value[0])
  t.lexer.skip(1) #Panic mode recovery. Skip one character

__file__ = "Untitled.ipynb" #FIX to work with Jupyter
lexer = lex.lex() # lexer object holds the ccreated lexer

lex.input("aab")
for tok in iter(lex.token, None):
    print(tok.type ,":", tok.value)`

Gives a different result every time I run it.
Best

**Comment by dabeaz** [comment]
PLY orders regex matching according the following rules:

1.  All rules defined by functions are matched in the order in which they are defined in the file.
2.  All rules defined by strings are then matched in sorted order according to the length of the regex pattern. 

I'm not really sure what you're trying to demonstrate with the above code, but it is generally an operational error in PLY to write multiple token rules that match the same text. 

Also, you're getting different results because Python dictionaries are unordered and are often randomized run-to-run of the interpreter.  PLY is pulling definitions from the module dictionary where the order is not predictable in any version of Python prior to Python 3.6.
