### ISSUE TITLE
Making the parser and lexer class-based

### ISSUE THREAD

**Issue by TMiguelT** [dabeaz/ply#91]
I think in the interests of making ply more pythonic, I think that we should provide a parser and lexer class that the users extend and add their parsing/lexing functions. The parser/lexer base class would then using getattr/hasattr to call these functions.

The advantage of this, is that we'd be firstly be removing the 'magic' from ply, (where it just grabs all functions from the current module starting with t_ or p_), which should make it more intuitive to use. Secondly, it allows for more logical namespacing of functions. At the moment, there can only be 1 parser/lexer per module which is a very strange convention.

I'm happy to do a PR with these changes but I was thinking of running it past the author first. If moving towards classes isn't in your plan then I might consider maintaining a fork of ply.

**Comment by johnyf** [comment]
One can organize their parser as a `class`, if they so want. This allows for multiple parsers within a single module, see [alternative specification of lexers](http://www.dabeaz.com/ply/ply.html#ply_nn17) and [multiple parsers and lexers](http://www.dabeaz.com/ply/ply.html#ply_nn37).

[`astutils`](https://github.com/johnyf/astutils) is a minimal module that provides skeleton classes using `ply`. For example, it has been used to define a [parser in one package](https://github.com/johnyf/promela/blob/8343ed1ef73cde7e60eb7c039ec53931c0235286/promela/yacc.py#L28) and [subclass this parser](https://github.com/johnyf/openpromela/blob/ccfc2abaab7d3793b6d9eda0165560669603d166/openpromela/logic.py#L56) in another package to create an extension of that language, by adding or overriding methods and attributes. Various examples of parsers that use `astutils` can be found in two other packages, [`dd`](https://github.com/johnyf/dd) and [`omega`](https://github.com/johnyf/omega).

Flat is better than nested (PEP 20), so it is likely better to keep PLY simple and transparent.
The `astutils` is an attempt to avoid the boilerplate. It also collects some lessons learned after trying several variants over a year of experimentation.

**Comment by TMiguelT** [comment]
Ah thanks for the links. I only read the github readme so I wasn't aware PLY could work with classes. I'll give astutils a go!

Nonetheless, don't you think PLY grabbing parser and lexer functions is the complete opposite of simple and transparent? I had to re-read the examples several times before I worked out how on earth the parser functions were being used by the parser. A far more pythonic version would either see them passed into the lex() or yacc() constructors, or like I said, extending the existing parser/lexer class and adding functions there (as in your astutils module)

**Comment by johnyf** [comment]
PLY introspecting the current namespace is implicit, not explicit, though explicit is better than implicit (PEP 20).
However, the application is complex, and already the interface hides a lot of the complexity.

It would be less practical to somehow explicitly mention which functions define productions.
One would have to list those functions. Each addition or deletion of a production rule would have to be done at two places: its definition, and the arguments of whatever constructor is used. This has great potential for repeatedly causing errors, and would be very distracting during debugging of a parser.

The issue remains within a class. The only purpose that a class serves is to provide a namespace for a set of production rules. Typically, a parser or lexer class has methods other than production rules. So, one would still need to define which methods are productions. The same errors would happen in this case.

Using the prefix `p_` is localized, and thus avoids errors of omission, which are more likely the farthest apart the method is from the call to the constructor where that method would have to be mentioned explicitly. So, in this way, `p_` could be regarded as being explicit, instead of implicit.

Besides, introspection is pythonic, and quite automated. After all, the prefix `p_` guards against naming conflicts with functions or methods in the same namespace, and serves as a common convention that allows to more easily read parsers written by others.

**Comment by TMiguelT** [comment]
>PLY introspecting the current namespace is implicit, not explicit, though explicit is better than implicit (PEP 20).
Indeed. This is exactly my point, and I believe it proves that this kind of reflection/introspection is unpythonic

>It would be less practical to somehow explicitly mention which functions define productions.
I didn't mention this earlier, but I disagree with this. There are many examples of frameworks that need to know about functions without wanting to list them twice. The best example of this is flask, which uses decorators on each function to pass them to the flask application and use them for routing requests.

```python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"
```

This, at least would solve the namespacing issue and also make sure the parser/lexer functions are explicitly passed into the parser/lexer. For example the API might look like this:

```python
lex = ply.lex()

@lex.token()
def NUMBER(t):
    r'\d+'
    t.value = int(t.value)
    return t
```

This isn't a class-based solution but I think it would solve all the issues I have with the API at very least

**Comment by TMiguelT** [comment]
Probably a better solution would be to pass in the token name in the decorator because my previous suggestion still needs some reflection. And also I think abusing docstrings to list the pattern should probably go since that's the epitome of implicit, as well as using docstrings for something they weren't designed. In addition I imagine this token() method could take just ordinary tokens without a function.

```python
lex = ply.lex()

@lex.token('NUMBER',  r'\d+')
def number(t):
    t.value = int(t.value)
    return t

lex.token('PLUS', r'\+')
```

**Comment by dabeaz** [comment]
PLY is more than 15 years old and predates the existence of new-style classes let alone decorators.  Limitations of the API are well known, but they will not be fixed in this project.   If and when they are fixed, it will be in a completely different project with a different name.

**Comment by TMiguelT** [comment]
Right in that case I'll go ahead and fork it at some point to try out my decorator based API. I don't think it should take too much effort since it'll only be a change of interface. The parser engine should stay relatively consistent.

**Comment by dabeaz** [comment]
Other projects have done similar things.  For example, rply uses decorators.  https://pypi.python.org/pypi/rply/0.5.1
